services:
  backend:
    build: ./vineyard-backend
    container_name: vineyard_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./vineyard-backend:/app
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: ./vineyard-backend
    container_name: vineyard_celery
    command: celery -A config worker -l info
    volumes:
      - ./vineyard-backend:/app
    depends_on:
      - backend
      - redis
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: vineyard_redis
    ports:
      - "6379:6379"

  frontend:
    build: ./vineyard-frontend
    container_name: vineyard_frontend
    volumes:
      - ./vineyard-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: postgres:16
    container_name: vineyard_postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
